# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# source 'https://cocoapods-cdn.netlify.app/'
source 'https://github.com/CocoaPods/Specs.git'

# source 'https://cdn.cocoapods.org/'
target 'CreditCardList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CreditCardList
  pod 'Kingfisher'
  pod 'lottie-ios'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  target 'CreditCardListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CreditCardListUITests' do
    # Pods for testing
  end

end
