# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COVID19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for COVID19
  pod 'Alamofire'
  pod 'Charts'
  target 'COVID19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'COVID19UITests' do
    # Pods for testing
  end

end
